dex:
  enabled: false
global:
  domain: argocd.140.245.69.143.nip.io
configs:
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
controller:
  clusterRoleRules:
    enabled: true
    rules:
    - apiGroups:
        - '*'
      resources:
        - '*'
      verbs:
        - '*'