settings:
  clusterName: practice
communications:
  'default-group':
    discord:
      enabled: true
      token: "${{ secrets.DISCORD_BOT_TOKEN }}"
      botID: "${{ secrets.DISCORD_BOT_ID }}" # botID 입력
      channels:
        'default':
          id: "${{ secrets.DISCORD_CHANNEL_ID }}" # channel id 입력
executors:
  k8s-default-tools:
    botkube/kubectl:
      displayName: "Kubectl"
      enabled: true
rbac:
  groups:
    'botkube-plugins-default':
      create: true
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]