settings:
  clusterName: practice
communications:
  'default-group':
    discord:
      enabled: true
      token: "{{ .Values.secret.discordToken }}" # 토큰 입력
      botID: "{{ .Values.secret.discordBotID }}" # botID 입력
      channels:
        'default':
          id: "{{ .Values.secret.discordChannelID }}" # channel id 입력
executors:
  k8s-default-tools:
    botkube/kubectl:
      displayName: "Kubectl"
      enabled: true
rbac:
  groups:
    'botkube-plugins-default':
      create: true
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]